version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672       # AMQP protocol
      - 15672:15672     # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333       # REST API
      - 6334:6334       # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  rabbitmq_data:
  qdrant_data:
